---
version: '3'
services:
  frontend:
    build:
      context: ./client
      dockerfile: dev.dockerfile
    volumes:
      - "./client:/usr/local/src"
      - "/usr/local/src/node_modules"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: dev.dockerfile
    volumes:
      - "./server:/usr/local/src"
      - "/usr/local/src/node_modules"
    depends_on:
      - db
    environment:
      MONGODB_URI: mongodb://db/app

  db:
    image: mongo:latest
    volumes:
      - "./data:/data/db"

  nginx:
    image: nginx:alpine
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend